{
  "hash": "905b0d1b4d6f028c4de18d20ae0bff62",
  "result": {
    "markdown": "---\ntitle: Explorer Fitness - 4\ndescription: Heart Rate Zone Training 4\nauthor: RJ Cody Markelz\ndate: 2023-09-28\ncategories: [GIS, data, exercise, quantified self, heart rate, cardio, training, adventure, explore, fitness, fire runner, explorer fitness, data journalism]\nimage: /images/zone_bar_plots-1.png\n---\n\n\n\n\n# Introduction\n\nThis post will focus on heart rate training progress over time from last year to early this season to a recent personal record on the same 13.15 km (8.17 mile) course with ~300m (984 ft) of elevation gain and loss. The two efforts are Zone 3/4 efforts. I like this course because it is technical, has some climbing, and I have done it enough that I know my splits at certain portions of the run for how well I am doing. \n\nFrom my trained perspective, the heart rate zones (HRZs) break down as follows:\n\n- < 120   - **Rest**   - Rest, recovery, daily living\n- 120-155 - **Zone 1** - Nose breathing pace, all-day pace\n- 156-162 - **Zone 2** - Avoid if possible, too hard for Zone 1, too easy for Zone 3\n- 163-173 - **Zone 3** - 1.5-hour pace for me, or many shorter bursts\n- 174-184 - **Zone 4** - Shorter **HARD** efforts\n- 185-195 - **Zone 5** - Pushing max pace/effort\n\n\nLoad the relevent libraries. \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(FITfileR)\nlibrary(tidyverse)\nlibrary(patchwork)\n```\n:::\n\n\nFor more information on each of the data import and processing steps, check out the previous [post](/posts/2023-09-01-explorer-exercise-3.html) in this series.\n\nRead in the data for a single run, process it to create heart rate zones, make a color vector for consistent color displays and do some basic plotting. \n\nThe run below is a Zone3/Zone4 heart rate zone run. This is my fastest time to date on this route at 1:00:31. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nRunZone3_Sept <- readFitFile(\"~/DATA/data/local-route-zone3-FKT.fit\") # load file\nRunZone3_Sept <- records(RunZone3_Sept) %>% bind_rows() %>% arrange(timestamp)\n\nRunZone3_Sept$HRzone <- cut(RunZone3_Sept$heart_rate,c(0,120,158,164,173,184, 200))\nlevels(RunZone3_Sept$HRzone) <- c(\"R\",\"Z1\",\"Z2\",\"Z3\",\"Z4\",\"Z5\")\nRunZone3_Sept$seconds <- as.numeric(rownames(RunZone3_Sept))\n\ncols3 <- c(\"R\" = \"#d4d4d4\",  \"Z1\" = \"#5192cb\", \"Z2\" = \"#4cbd57\", \n          \"Z3\" = \"#e4e540\", \"Z4\"= \"#ffb217\", \"Z5\" = \"#ff5733\", \"NA\" = \"#454545\")\n\nz3_p <- ggplot(RunZone3_Sept, aes(x=seconds,  y=heart_rate, col=HRzone)) +\n      geom_point() +\n      scale_x_continuous(name=\"Time (Seconds)\") +\n      scale_y_continuous(limits = c(100, 200), name=\"Heart Rate (bpm)\") +\n      scale_color_manual(values = cols3) +\n      ggtitle(\"September 2023\")\nz3_p\n```\n\n::: {.cell-output-display}\n![](2023-09-28-explorer-exercise-4_files/figure-html/zone3_sept_2023-1.png){width=672}\n:::\n:::\n\nNow we can take a look at the elevation profile of the run. A majority of the gain is in the first 30 minutes of the run, then it is rolling hills with a net down for the rest of the run. The steepest sustained section nearly always ensures I am at the Zone 3/4 threshold. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nz3_p_alt <- ggplot(RunZone3_Sept, aes(x=seconds,  y=altitude)) +\n      geom_point() +\n      scale_x_continuous(name=\"Time (Seconds)\") +\n      scale_y_continuous(name=\"Elevation (m)\")\nz3_p_alt\n```\n\n::: {.cell-output-display}\n![](2023-09-28-explorer-exercise-4_files/figure-html/zone3_elevation-1.png){width=672}\n:::\n:::\n\n\n---\n\nHow do I know that I am getting faster? We could just look at raw times, but we can also compare heart rate zones across time on the same course. This can give a better indication of how well my training is contributing to hard efforts over time.\n\nLoad and process the comparison run from September 2022. \n\n::: {.cell}\n\n```{.r .cell-code}\nRunZone3_2022 <- readFitFile(\"~/DATA/data/local-route-2022-2nd-place.fit\") # load file\nRunZone3_2022 <- records(RunZone3_2022) %>% bind_rows() %>% arrange(timestamp)\n\nRunZone3_2022$HRzone <- cut(RunZone3_2022$heart_rate,c(0,120,158,164,173,184, 200))\nlevels(RunZone3_2022$HRzone) <- c(\"R\",\"Z1\",\"Z2\",\"Z3\",\"Z4\",\"Z5\")\nRunZone3_2022$seconds <- as.numeric(rownames(RunZone3_2022))\n```\n:::\n\n\nA quick comparison in times for each of the runs. \n\n::: {.cell}\n\n```{.r .cell-code}\nmax(RunZone3_Sept$seconds) # September 2023\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3619\n```\n:::\n\n```{.r .cell-code}\nmax(RunZone3_2022$seconds) # September 2022\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3718\n```\n:::\n:::\n\n3619 seconds for September 2023 and 3718 seconds for September of last year. \n\nI have gotten faster in absolute terms, but have I gotten faster for a given heart rate? We will start to answer that question by looking at comparison plots between the runs. \n\nTo stack the plots we will use the [Patchwork R package](https://cran.r-project.org/web/packages/patchwork/index.html) functions. \n\n::: {.cell}\n\n```{.r .cell-code}\nz322_p <- ggplot(RunZone3_2022, aes(x=seconds,  y=heart_rate, col=HRzone)) +\n      geom_point() +\n      scale_x_continuous(name=\"Time (Seconds)\") +\n      scale_y_continuous(limits = c(100, 200), name=\"Heart Rate (bpm)\") +\n      scale_color_manual(values = cols3) +\n      ggtitle(\"September 2022\")\n\nstacked_plots <- z3_p / z322_p +  plot_layout(ncol = 1, heights = c(10, 10))\nstacked_plots\n```\n\n::: {.cell-output-display}\n![](2023-09-28-explorer-exercise-4_files/figure-html/zone3_data-1.png){width=672}\n:::\n:::\n\n\n---\n\nWe can take a look at the accumulated number of seconds spent in each of the various heart rate zones:\n\n::: {.cell}\n\n```{.r .cell-code}\nz3_p2 <- ggplot(RunZone3_Sept, aes(x=HRzone, fill=HRzone)) +\n      geom_bar(na.rm = TRUE) +\n      scale_y_continuous(limits = c(0, 1750), name=\"Seconds in HR Zone\") +\n      scale_fill_manual(values = cols3) + \n      scale_x_discrete(na.translate = FALSE) +\n      ggtitle(\"September 2023\")\n\nz322_p2 <- ggplot(RunZone3_2022, aes(x=HRzone, fill=HRzone)) +\n      geom_bar(na.rm = TRUE) +\n      scale_y_continuous(limits = c(0, 1750), name=\"Seconds in HR Zone\") +\n      scale_fill_manual(values = cols3) + \n      scale_x_discrete(na.translate = FALSE) +\n      ggtitle(\"September 2022\")\n\nstacked_plots2 <- z3_p2  / z322_p2 +  plot_layout(ncol = 1, heights = c(4, 4))\nstacked_plots2\n```\n\n::: {.cell-output-display}\n![](2023-09-28-explorer-exercise-4_files/figure-html/zone123_bar_plots-1.png){width=672}\n:::\n:::\n\nWith all the accumulated cardio training I can now run a faster time for this course with a much lower average heart rate and much less time of the run spent in Zone 4. My top time is spent mostly in Zone 3. This is in comparison to June 2023 which had more time spent in Zone 4. \n\nOverall, my fitness training is paying off!\n\n---\n\nIf you are interested in other posts in this explorer series check out [Explorer Fitness 1](/posts/2023-07-07-explorer-exercise-1.html), [Explorer Fitness 2](/posts/2023-07-21-explorer-exercise-2.html), [Explorer Fitness 3](/posts/2023-09-01-explorer-exercise-3.html) and [Trail Running Training](/posts/2022-08-15-trailrunningtrainingdata/).\n",
    "supporting": [
      "2023-09-28-explorer-exercise-4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}